language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Others
  - ./download_other_githubs


# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Console test
  - qmake -qt=qt5 ReversiConsoleTest.pro
  - make --silent debug
  - ./ReversiConsoleTest & 
  # Console
  - qmake -qt=qt5 ReversiConsole.pro
  - make --silent debug
  # - ./ReversiConsole & # Don't
  # Desktop test
  - qmake -qt=qt5 ReversiDesktop.pro
  - make --silent debug
  - ./ReversiDesktop &
  # Code coverage
  - ./get_code_cov > /dev/null
  - codecov > /dev/null
  # OCLint
  - ./do_oclint || true

after_success: 
  - bash <(curl -s https://codecov.io/bash)
